# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Miloš Petrašinović
title: Software Developer
email: milos.petrasin@gmail.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
# website: Your website (eg. https://google.com)(optional)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
twitter_username: mpetrasin
github_username:  petrasin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: petrasin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: /images/profile.webp
about_content: |
  Hi, my name is Miloš, I'm a software developer with over a decade of professional experience currently specializing in Cloud Native development. I am currently working for SAP as a Lead Software Engineer on their cloud-based incentive and compensation management software, Commissions.

  I have worked with a range of different languages and frameworks and I am always paying attention to new technologies to stay ahead of the curve. I take pride in following industry standards and best practices, writing well-structured and clean code, and organizing my code in a scalable manner. I also love to share my knowledge with my team members, always happy to help and make sure everyone on the team is up to speed. 

  The things that I have the most experience working with are:
   - Programming languages: <mark>Java</mark> <mark>Kotlin</mark> <mark>Groovy</mark>
   - Frameworks: <mark>Spring</mark> <mark>Angular</mark> <mark>Hibernate</mark> <mark>Apache Camel</mark>
   - Web: <mark>Javascript</mark> <mark>Typescript</mark> <mark>HTML</mark> <mark>CSS</mark> <mark>REST</mark>
   - Build tools: <mark>Gradle</mark> <mark>Maven</mark>
   - Cloud technologies: <mark>Docker</mark> <mark>GCP</mark>
   - Databases: <mark>Oracle</mark> <mark>Hana</mark> <mark>PostgreSQL</mark> <mark>MongoDB</mark> <mark>H2</mark>
   - Testing: <mark>Junit 5</mark> <mark>Mockito</mark> <mark>JMeter</mark> <mark>Cypress</mark> <mark>Testcontainers</mark>
   - CI/CD: <mark>Jenkins</mark> <mark>SonarCloud</mark> <mark>GitHub Actions</mark>
   - Version control systems: <mark>Git</mark> <mark>Mercurial</mark> <mark>Subversion</mark> <mark>Perforce</mark>
   - Non-technical skills: <mark>Problem-solving</mark> <mark>Teamwork</mark> <mark>Agile development</mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: SAP West Balkans
        sub_title: Lead Software Engineer
        caption: March 2019 - Present
        link: www.sap.com
        description: |
          As a lead software engineer with a cloud-native mindset, I bring a unique blend of technical expertise and problem-solving skills to my work, particularly in the area of microservices. I am a valuable member of the team at SAP, where I have consistently demonstrated my ability to lead and mentor other engineers while delivering innovative solutions that meet the evolving needs of our business.
          
          In my role as lead software engineer at SAP, I have made the following contributions:
          - Designed and implemented a backup and restore solution for the Commissions product, supporting both <mark>Hana</mark> and <mark>Oracle</mark> databases.
          - Implemented a robust security solution using <mark>Spring Security</mark> and <mark>OAuth2</mark>, enhancing the overall security posture of the products.
          - Built and maintained a <mark>CI/CD</mark> pipeline using <mark>Jenkins</mark>.
          - Led architecture decisions and follows a strict <mark>TDD</mark> approach.
          - Actively engaged in code reviews and provided constructive feedback to peers.
          - Participated in bug fixes, ensuring smooth and efficient operation of the systems.
          - Participated in various technology trainings offered by the company, further expanding my skill set.
          - Currently involved in the effort to rewrite a monolithic application as a microservices-based solution.
          
      - layout: left
        border: weak
        title: Finbet
        sub_title: Software Developer
        caption: Jul 2013 - March 2019
        link: finbet.rs
        description: |
          While I worked at Finbet, I was a software engineer focused on delivering high-quality solutions for the company's sports betting platform, <mark>MM1</mark> (Margin Maker 1). I was responsible for writing integration services and contributing to the development of the BonusEngine service.
          My time at Finbet provided me with valuable experience in the online betting industry and I am grateful for the opportunities I had to grow both professionally and personally.
          - Developed integration services using <mark>Apache Camel</mark> and <mark>Oracle Service Bus</mark>.
          - Worked on the Bonus Engine Service that provided bonuses for users, using the <mark>Spring</mark> framework.
          - Integration with gambling regulatory authority utilizing <mark>TLS</mark>.
          - Implemented services that use <mark>Oracle Coherence</mark>, distributed in-memory cache.
          - Worked on the development of a virtual horse racing betting game, utilizing <mark>Spring Boot</mark>, <mark>Angular</mark>, and <mark>Maven</mark>.
          - Followed and implemented General Data Protection Regulation (GDPR) standards in all projects and operations.
          - Deployed services on <mark>WebLogic</mark>, <mark>Tomcat</mark>, <mark>JBoss</mark> application servers. 
          - Worked with development teams to identify and resolve integration issues, resulting in improved stability and performance of the platform.
      - layout: left
        border: weak
        title: RCUB
        sub_title: Software Developer
        caption: October 2010 - June 2013
        link: rcub.bg.ac.rs       
        description: | 
          During my time at University of Belgrade Computer Center as a Software Developer, I was responsible for the development and launch of a Google Web Toolkit web application that aggregated network events using Java and collaborated with a team of developers to maintain and improve the application.
          - Developed a <mark>GWT</mark> web application that aggregates network events (syslog, SNMP Trap) using <mark>Java</mark>.
          - Implemented a persistence solution using <mark>OpenJPA</mark> and <mark>PostgreSQL</mark>.
          - Utilization of <mark>UDP</mark> transport protocol.
          - Worked with a team of developers to design, implement, and maintain the application.
          - Participated in code reviews, debugging, and testing to ensure the application met quality standards.
          - [www.netvizura.com/eventlog-analyzer](https://www.netvizura.com/eventlog-analyzer)
      - layout: left
        title: Microsoft Development Center Serbia
        sub_title: Data Collection & Labeling Associate
        caption: June 2010 - March 2011
        link: www.microsoft.com/en-rs/mdcs
        description: | 
          As an intern at Microsoft, I was responsible for supporting the development and testing of the company's Optical Character Recognition engine.
          - Collected, sampled and labeled data for <mark>OCR</mark> engine developed by the company.
          - Evaluated the sampled data to identify any bugs or issues.
          - Contributed to the development of a sampling strategy to improve the accuracy of the OCR engine.
  - title: Education
    layout: list
    content:
      - layout: top-left
        title: University of Belgrade
        sub_title: School of Electrical Engineering, B.A.Sc. Computer Science
        caption: 2006 - 2011
        link: www.etf.bg.ac.rs
        description: |
          I studied at the University of Belgrade where I obtained a degree in Computer Science. During my time there, I gained extensive knowledge in computer architecture and software development, as well as programming algorithms. My education was reinforced through various hands-on projects and assignments which helped me to solidify my understanding of these concepts.
          
  - title: When I'm away from keyboard
    layout: text
    content: |
      In my free time, I enjoy spending time with my family. I am also a passionate cyclist and mountain climber, and on weekends I often team up with friends to go on tours or climb mountains. I also enjoy tinkering with electronics, setting up home servers, and working with multimedia. I'm in a process of starting a YouTube channel to share videos about my adventures.

      I like to keep active and challenge myself in both my personal and professional life.

      <img src="/images/mountain.webp" alt="Mountain">

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
